version: 0.2
env:
  variables:
    BUILD_VERSION: "1.0.0"
    AWS_REGION: "ap-southeast-1"
    ECR_REPO: "576694912472.dkr.ecr.ap-southeast-1.amazonaws.com"
    #    DOCKERFILE_commons: "./quarkushop-commons/Dockerfile"
    DOCKERFILE_customer: "./quarkushop-customer/src/main/docker/Dockerfile.native"
    DOCKERFILE_order: "./quarkushop-order/src/main/docker/Dockerfile.native"
    DOCKERFILE_product: "./quarkushop-product/src/main/docker/Dockerfile.native"
    DOCKERFILE_user: "./quarkushop-user/src/main/docker/Dockerfile.native"

phases:
  pre_build:
    commands:
       # Install AWS CLI
#      - apt-get update && apt-get install -y --no-install-recommends python3-pip && pip3 install --upgrade awscli && apt-get clean && rm -rf /var/lib/apt/lists/*
#      # Install required dependencies and update the package manager
#      - apt-get update
#      - apt-get install -y --no-install-recommends apt-transport-https ca-certificates curl gnupg lsb-release
#
#      # Add Docker's official GPG key
#      - curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
#
#      # Add Docker's repository to sources
#      - echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
#      - curl -fsSL get.docker.com | CHANNEL=stable sh
#      - apt install docker-ce
#      - apt-get install docker-ce docker-ce-cli containerd.io
#      - apt-get update
#      - apt-get install -y fuse-overlayfs

      #      # Install Docker
#      - apt-get update
#      - apt-get install -y --no-install-recommends docker-ce docker-ce-cli containerd.io
      - docker --version
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO

  build:
    commands:
      - ls
      # Build and push quarkusshop-common
#      - cd quarkushop-commons
#      - docker build -t YOUR_ECR_REPO_URL_COMMON:latest .
#      - docker push YOUR_ECR_REPO_URL_COMMON:latest
      - mvn clean install -DskipTests

      # Build and push event-statistics
      - cd department-service
#      - mvn package -Pnative -Dquarkus.native.container-build=true
      - ls
      - mv ./src/main/docker/Dockerfile.jvm ./Dockerfile
      - ls
      - docker --help
#      - dockerd
      - docker build -t $ECR_REPO/department-service:latest .
      - docker push "$ECR_REPO/department-service:latest"
      - mv Dockerfile Dockerfile.jvm
      - cd ..
      - ls

      # Build and push rest-fights
      - cd employee-service
      - mv ./src/main/docker/Dockerfile.jvm ./Dockerfile
      - docker build -t $ECR_REPO/employee-service:latest .
      - docker push "$ECR_REPO/employee-service:latest"
      - mv Dockerfile Dockerfile.jvm
      - cd ..
      - ls

      # Build and push rest-heroes
      - cd organization-service
      - mv ./src/main/docker/Dockerfile.jvm ./Dockerfile
      - docker build -t $ECR_REPO/organization-service:latest .
      - docker push "$ECR_REPO/organization-service:latest"
      - mv Dockerfile Dockerfile.jvm
      - cd ..
      - ls

#      # Build and push rest-villains
#      - cd rest-villains
#      - mv ./src/main/docker/Dockerfile.jvm ./Dockerfile
#      - docker build -t $ECR_REPO/rest-villains:latest .
#      - docker push "$ECR_REPO/rest-villains:latest"
#      - mv Dockerfile Dockerfile.jvm
#      - cd ..
#      - ls
#
#      # Build and push ui-super-heroes
#      - cd ui-super-heroes
#      - mv ./src/main/docker/Dockerfile.jvm ./Dockerfile
#      - docker build -t $ECR_REPO/ui-super-heroes:latest .
#      - docker push "$ECR_REPO/ui-super-heroes:latest"
#      - mv Dockerfile Dockerfile.jvm
#      - cd ..
#      - ls
  post_build:
    commands:
      # Deploy to ECS
      - aws ecs update-service --cluster quarkus --service event-statistics --force-new-deployment
artifacts:
  files: []
